###

GET http://localhost:8080/

###

GET http://localhost:8080/produto

###

GET http://localhost:8080/produto/1

###

POST http://localhost:8080/produto
Content-Type: application/json

{
    "nome": "Maça",
    "descricao": "Fruta",
    "preco": 1.75,
    "tags": ["F1", "M2", "V3"]
}

###

PUT http://localhost:8080/produto/1
Content-Type: application/json

{
    "nome": "Novo nome",
    "descricao": "Nova desc",
    "preco": 100
}

###

DELETE http://localhost:8080/produto/1
